### ISSUE TITLE
stripHTML() undefined

### ISSUE THREAD

**Issue by celsomiranda** [hexojs/util#1]
``` node
Possibly unhandled TypeError: c:\gh\celsomiranda.github.io\themes\hexlog\layout\index.jade:25
    23|           .post-content
    24|             != truncate(article.content, {length: 186, omission: '&hellip;', separator: ' '}
)
  > 25|             p=stripHTML(article.content)
    26|
    27|         footer.post-footer
    28|           a(href=config.root + article.path).more= __('index.more')

undefined is not a function
    at jade_debug.unshift.lineno (eval at <anonymous> (c:\gh\celsomiranda.github.io\node_modules\hex
o-renderer-jade\node_modules\jade\lib\index.js:218:8), <anonymous>:402:54)
    at eval (eval at <anonymous> (c:\gh\celsomiranda.github.io\node_modules\hexo-renderer-jade\node_
modules\jade\lib\index.js:218:8), <anonymous>:538:4)
    at eval (eval at <anonymous> (c:\gh\celsomiranda.github.io\node_modules\hexo-renderer-jade\node_
modules\jade\lib\index.js:218:8), <anonymous>:609:22)
    at res (c:\gh\celsomiranda.github.io\node_modules\hexo-renderer-jade\node_modules\jade\lib\index
.js:219:38)
    at Hexo.<anonymous> (c:\gh\celsomiranda.github.io\node_modules\hexo-renderer-jade\index.js:4:56)

    at Hexo.tryCatcher (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebi
rd\js\main\util.js:24:31)
    at Hexo.<anonymous> (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\blueb
ird\js\main\method.js:15:34)
    at Promise.then.then.output (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\lib\hexo\r
ender.js:51:21)
    at tryCatcher (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js
\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\n
ode_modules\bluebird\js\main\promise.js:466:31)
    at Promise._settlePromiseAt (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modul
es\bluebird\js\main\promise.js:545:18)
    at Promise._settlePromiseAtPostResolution (c:\Users\celso_000\AppData\Roaming\npm\node_modules\h
exo\node_modules\bluebird\js\main\promise.js:229:10)
    at Async._drainQueue (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\blue
bird\js\main\async.js:84:12)
    at Async._drainQueues (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\blu
ebird\js\main\async.js:89:10)
    at Async.drainQueues (c:\Users\celso_000\AppData\Roaming\npm\node_modules\hexo\node_modules\blue
bird\js\main\async.js:14:14)
    at process._tickCallback (node.js:442:13)
```

**Comment by tommy351** [comment]
This bug is not related to util itself. It's becuase the helper is named `strip_html` in Hexo. I'll add `stripHTML` as an alias later.
